### ISSUE TITLE
mix-manifest.json gets modified when running test.

### ISSUE THREAD

**Issue by jimmypuckett** [laracasts/testingvue#1]
The ```mix-manifest.json``` file gets modified when I run test.

I have this...

```js
"test": "mocha-webpack --webpack-config node_modules/laravel-mix/setup/webpack.config.js --require tests/setup.js \"tests/**/*.test.js\"",
```

in my package.json file.

When I run the test ```yarn run test```, the ```mix-manifest.json``` becomes...

```json
{
    "/994b0d397ed25c91c15333907c7d5662-output.js": "/994b0d397ed25c91c15333907c7d5662-output.js"
}
```

instead of...

```json
{
    "/js/app.js": "/js/app.js",
    "/css/app.css": "/css/app.css",
    "/css/site.css": "/css/site.css",
    "/js/site.js": "/js/site.js"
}
```

Can you update the episode 6 to show how to correct this issue?

Thanks.

**Comment by edtownend** [comment]
Hugely late reply but after a lot of fiddling the easiest solution I came up with was to change the public path for testing builds so the generated mix-manifest ends up in the tests directory. I did this by setting a testing environment variable before the testing script in package.json:

`"test-js": "cross-env NODE_ENV=testing mocha-webpack --webpack-config=node_modules/laravel-mix/setup/webpack.config.js --require tests/Js/setup.js tests/Js/\\*\\*/\\*.spec.js",
`
then in in my webpack.mix.js:

`
if (process.env.NODE_ENV === 'testing') {
    mix.setPublicPath('tests');
}
`

and finally gitignore texts/mix-manifest.json. Means we can use the same webpack.mix.config for all environments.

Hope it helps!
